config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                       erd        /erd                                                                                     Erd::Engine
#                      root GET    /                                                                                        pages#index
#               new_session GET    /sessions/new(.:format)                                                                  sessions#new
#                  sessions POST   /sessions(.:format)                                                                      sessions#create
#                           DELETE /sessions(.:format)                                                                      sessions#destroy
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                     users POST   /users(.:format)                                                                         users#create
#                      user GET    /users/:id(.:format)                                                                     users#show
#             user_expenses GET    /users/:id/expenses(.:format)                                                            expenses#index
#          new_user_expense GET    /users/:id/expenses/new(.:format)                                                        expenses#new
#                  expenses POST   /expenses(.:format)                                                                      expenses#create
#                    groups GET    /groups(.:format)                                                                        groups#index
#                           POST   /groups(.:format)                                                                        groups#create
#                 new_group GET    /groups/new(.:format)                                                                    groups#new
#                     group GET    /groups/:id(.:format)                                                                    groups#show
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for Erd::Engine:
#         GET  /                  erd/erd#index
#         PUT  /                  erd/erd#update
# migrate PUT  /migrate(.:format) erd/erd#migrate
#    root GET  /                  erd/erd#index

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/sessions/new', to: 'sessions#new', as: 'new_session'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'

  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/users/:id/expenses', to: 'expenses#index', as: 'user_expenses'
  get '/users/:id/expenses/new', to: 'expenses#new', as: 'new_user_expense'
  post '/expenses', to: 'expenses#create'

  resources :groups, only: %i[index new create]
  get '/group/:group_id/expenses', to: 'expenses#index', as: 'group'
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  icon       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Group < ApplicationRecord
  has_and_belongs_to_many :expenses
  before_destroy do
    expenses.each(&:destroy)
  end

  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all.order(:name)
  end

  def show

  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group[:icon] = 'logo.png' if @group[:icon].empty?
    if @group.save
      flash[:notice] = 'Group was successfully created.'
      redirect_to groups_path
    else
      @group[:icon] = ''
      flash.now[:alert] = 'Group could not be created.'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/views/groups/index.html.erb
<main class="user-groups pt-5">
  <% @current_page = '> All groups' %>
  <ul class="groups-list simple-list d-flex flex-column p-0">
    <% @groups.each do |group| %>
      <%= link_to group_path(group.id, group: true), class: 'group-link' do %>
        <li class="card m-1">
          <div class="card-body p-1 d-flex flex-row">
            <%=image_tag group.icon, alt: group.name, class: "group-icon"%>
            <div class="name-date">
              <span class="name"><%= group.name %></span>
              <span class="date">Since: <%= group.created_at.strftime("%m/%d/%Y") %></span>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to 'Add group', new_group_path, class: 'new-btn' %>
  <% @footer = false %>
</main>

app/views/groups/new.html.erb
<main class="new-group py-5">
  <% @current_page = '> New group' %>
  <div class="form-group text-left border border-light p-3">
  <p class="h5 mb-3">New group</p>
  <%= form_with model: @group, local: true do |f| %>
    <ul class="list-unstyled text-danger">
      <% @group.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    <%= f.text_field :name, placeholder: 'Group name*', class: 'form-control', required: true %><br>
    <%= f.text_field :icon, placeholder: 'Group icon image URL', class: 'form-control' %>
    <%= f.submit 'Create Group', class: 'btn btn-info btn-block mb-2 mt-4' %>
  <% end %>
  </div>
</main>