config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                       erd        /erd                                                                                     Erd::Engine
#                      root GET    /                                                                                        pages#index
#               new_session GET    /sessions/new(.:format)                                                                  sessions#new
#                  sessions POST   /sessions(.:format)                                                                      sessions#create
#                           DELETE /sessions(.:format)                                                                      sessions#destroy
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                     users POST   /users(.:format)                                                                         users#create
#                      user GET    /users/:id(.:format)                                                                     users#show
#             user_expenses GET    /users/:id/expenses(.:format)                                                            expenses#index
#          new_user_expense GET    /users/:id/expenses/new(.:format)                                                        expenses#new
#                  expenses POST   /expenses(.:format)                                                                      expenses#create
#                    groups GET    /groups(.:format)                                                                        groups#index
#                           POST   /groups(.:format)                                                                        groups#create
#                 new_group GET    /groups/new(.:format)                                                                    groups#new
#                     group GET    /groups/:id(.:format)                                                                    groups#show
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for Erd::Engine:
#         GET  /                  erd/erd#index
#         PUT  /                  erd/erd#update
# migrate PUT  /migrate(.:format) erd/erd#migrate
#    root GET  /                  erd/erd#index

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/sessions/new', to: 'sessions#new', as: 'new_session'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'

  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/users/:id/expenses', to: 'expenses#index', as: 'user_expenses'
  get '/users/:id/expenses/new', to: 'expenses#new', as: 'new_user_expense'
  post '/expenses', to: 'expenses#create'

  resources :groups, only: %i[index new create]
  get '/group/:group_id/expenses', to: 'expenses#index', as: 'group'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupExpenses</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8e996abce9.js"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <% if current_user %>
      <nav class='d-flex justify-content-end px-3 bg-dark'>
        <%= link_to '<i class="fas fa-home"></i>'.html_safe, root_path, class: 'home-link' %>
        <span class='current-page mr-auto ml-1'><%= @current_page %></span>
        <%= link_to current_user.username, user_path(current_user.id), class: 'profile-link mr-2' %>
        <%= link_to "Logout", sessions_path, method: 'delete', class: 'signout-link' %>
      </nav>
    <% end %>
    <% flash.each do |type, msg| %>
      <div class="text-center position-absolute mt-2 px-4 alert alert-<%= notice_or_alert(type) %>">
        <%= msg %>
      </div>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="col-12 text-center position-static">
          <%= yield %>
        </div>
      </div>
    </div>

    <% unless @footer == false %>
    
    <footer class="footer bg-light border text-center mt-auto">
      <span>Copyright &copy; 2020</span>
    </footer>
    <% end %>

    <script type="text/javascript">
      $(document).ready(function(){
          setTimeout(() => $('.alert').slideUp(), 3000);
      });
    </script>
  </body>
</html>